// js/data.js — dataset lokal untuk testing
export const products = [
  {
    id: 1,
    title: "Essence Mascara Lash Princess",
    price: 9.99,
    rating: 2.56,
    stock: 99,
    category: "beauty",
    tags: ["beauty", "mascara"],
    dimensions: { width: 15.14, height: 13.08, depth: 22.99 },
    reviews: [
      { user: "Eleanor Collins", rating: 3, comment: "Would not recommend!" },
      { user: "Lucas Gordon", rating: 4, comment: "Very satisfied!" },
      { user: "Eleanor Collins", rating: 5, comment: "Highly impressed!" },
    ],
  },
  {
    id: 4,
    title: "Red Lipstick",
    price: 12.99,
    rating: 4.36,
    stock: 91,
    category: "beauty",
    tags: ["beauty", "lipstick"],
    dimensions: { width: 18.11, height: 28.38, depth: 22.17 },
    reviews: [
      { user: "Liam Garcia", rating: 4, comment: "Great product!" },
      { user: "Ruby Andrews", rating: 5, comment: "Great product!" },
      { user: "Clara Berry", rating: 5, comment: "Would buy again!" },
    ],
  },
  {
    id: 6,
    title: "Calvin Klein CK One",
    price: 49.99,
    rating: 4.37,
    stock: 29,
    category: "fragrances",
    tags: ["fragrances", "perfumes"],
    dimensions: { width: 29.36, height: 27.76, depth: 20.72 },
    reviews: [
      { user: "Layla Young", rating: 2, comment: "Very disappointed!" },
      { user: "Daniel Cook", rating: 4, comment: "Fast shipping!" },
      { user: "Jacob Cooper", rating: 3, comment: "Not as described!" },
    ],
  },
  {
    id: 8,
    title: "Dior J'adore",
    price: 89.99,
    rating: 3.8,
    stock: 98,
    category: "fragrances",
    tags: ["fragrances", "perfumes"],
    dimensions: { width: 27.67, height: 28.28, depth: 11.83 },
    reviews: [
      { user: "Nicholas Bailey", rating: 5, comment: "Great value for money!" },
      { user: "Penelope Harper", rating: 4, comment: "Great value for money!" },
      { user: "Emma Miller", rating: 4, comment: "Great product!" },
    ],
  },
  {
    id: 14,
    title: "Knoll Saarinen Executive Conference Chair",
    price: 499.99,
    rating: 4.88,
    stock: 26,
    category: "furniture",
    tags: ["furniture", "office chairs"],
    dimensions: { width: 13.81, height: 7.5, depth: 5.62 },
    reviews: [
      { user: "Ella Cook", rating: 2, comment: "Waste of money!" },
      { user: "Clara Berry", rating: 2, comment: "Very dissatisfied!" },
      { user: "Elena Long", rating: 5, comment: "Would buy again!" },
    ],
  },
  {
    id: 16,
    title: "Apple",
    price: 1.99,
    rating: 4.19,
    stock: 8,
    category: "groceries",
    tags: ["fruits"],
    dimensions: { width: 13.66, height: 11.01, depth: 9.73 },
    reviews: [
      { user: "Sophia Brown", rating: 5, comment: "Very satisfied!" },
      { user: "Scarlett Bowman", rating: 1, comment: "Very dissatisfied!" },
      {
        user: "William Gonzalez",
        rating: 3,
        comment: "Very unhappy with my purchase!",
      },
    ],
  },
  {
    id: 30,
    title: "Kiwi",
    price: 2.49,
    rating: 4.93,
    stock: 99,
    category: "groceries",
    tags: ["fruits"],
    dimensions: { width: 19.4, height: 18.67, depth: 17.13 },
    reviews: [
      { user: "Emily Brown", rating: 4, comment: "Highly recommended!" },
      { user: "Jackson Morales", rating: 2, comment: "Would not buy again!" },
      { user: "Nora Russell", rating: 4, comment: "Fast shipping!" },
    ],
  },
];
